server:
  port: ${PORT:0}
  
spring:
  application:
    name: courses-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springcloudyangular9?currentSchema=courses
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non-null
    
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka